[basic]
api_base = "https://api.deepseek.com/v1"
model = "deepseek-chat"
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[clarify]
api_base = "https://api.deepseek.com/v1"
model = "deepseek-chat"
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[planner]
api_base = "https://api.deepseek.com/v1"
model = "deepseek-reasoner"
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[query_generation]
api_base = "https://api.deepseek.com/v1"
model = "deepseek-chat"
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[evaluate]
api_base = "https://api.deepseek.com/v1"
model = "deepseek-chat"
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[report]
api_base = "https://api.deepseek.com/v1"
model = "deepseek-chat"
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
