[search]
# search engine (supports "jina" or "tavily" now)
engine = "tavily"
timeout = 30
jina_api_key = "jina_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
tavily_api_key = "tvly-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"